### ISSUE TITLE
Error parsing config file config.yml: yaml: found character that cannot start any token

### ISSUE THREAD

**Issue by mzch** [lixmal/gdprshare#1]
What's wrong...? I added `_ "github.com/jinzhu/gorm/dialects/mysql"` to `main.go`.
And pass `http://www.yamllint.com/`

```yaml
# post size in MiB
maxuploadsize: 1000

idlength: 20

# directory to store uploaded files
storepath: '/srv/gdprshare/files'

# listen address/port
listenaddr: '127.0.0.1:28888'

tls:
  use:  false
  key:  '/etc/ssl/private/ssl-cert-snakeoil.key'
  cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'

# see https://godoc.org/github.com/jinzhu/gorm#Open
database:
  driver: 'mysql'
  args:   'gdprshare:password@127.0.0.1/gdprshare?charset=utf8mb4&parseTime=True&loc=Local'

mail:
  smtphost: 'smtp.example.com'
  smtpport: 587
  smtpuser: 'admin@example.com'
  smtppass: 'password'
  from:     'no-reply@example.com'
  subject:  'File was downloaded: %s'
  body:     'File with id {{.FileID}} was downloaded.'
# available variables:
#   .FileID
#   .Addr
#   .UserAgent
#   .SrcTLSVersion
#   .SrcTLSCipherSuite
#   .DstTLSVersion
#   .DstTLSCipherSuite

# headers in case app is behind a reverse proxy
header:
  tlsversion:     'X-TLS-Version'
  tlsciphersuite: 'X-TLS-CipherSuite'

# saves receiver IP addr and user agent in database
saveclientinfo: false

# length of password pregenerated on the frontend
passwordlength: 12

# for config via env vars see https://github.com/jinzhu/configor#advanced-usage
```
